# Generated by Django 5.0.3 on 2024-03-05 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mainImage', models.ImageField(upload_to='color_palettes/')),
            ],
        ),
        migrations.CreateModel(
            name='PaletteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='palette_images/')),
                ('color_palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otherImages', to='front.colorpalette')),
            ],
        ),
    ]
